server:
  servlet:
    context-path: /api
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method
    disable-swagger-default-url: true
  writer-with-default-pretty-printer: true
  default-produces-media-type: application/json
  override-with-generic-response: true
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/dev-whu?useSSL=false&serverTimezone=UTC
    username: root
    password: LDroot2406
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true