server:
  servlet:
    context-path: /api
springdoc:
  api-docs:
    groups:
      enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    disable-swagger-default-url: true
  writer-with-default-pretty-printer: true
  default-produces-media-type: application/json
  override-with-generic-response: true

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
  expiration: 3600





spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev-whu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: LDroot2406
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
