###
POST http://localhost:8080/api/proxy/release
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMTEiLCJleHAiOjE3MzM3Njc4NzcsImlhdCI6MTczMzczMTg3Nywic2NvcGUiOiIifQ.rt386YK-MYXR1CLJTLIP4UVh_--1nKH941DmEpdYJhtBONZPvysv68fpwL-uiJOhUl4sj2Hw1UuMPhyMdGVpW2L2678P5zud5N3hlO-qAXwMUjnJzZQ6Mgn-i7-o4TDycO7u_17-aIp01d20tGatuYzR1q6-oPRLHl5yWcfcE5br8oJTLxtaeGgPzZtJs1EtfBS0g_DsQwDkUJWtAedMELPWNR7ZggvaZnUtxCFpvBrQd8na4Q6dYoOrFaTuwRwFCTchgKF91tupWxNIahpMgaUGSsJF00rAVK6mNFtKJsB9GjFtJ0-PwJfe7BwUausQyINrUKoZcMEuiqmKJ9gj4g

###
GET http://localhost:8080/api/proxy
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMTEiLCJleHAiOjE3MzM3Njc4NzcsImlhdCI6MTczMzczMTg3Nywic2NvcGUiOiIifQ.rt386YK-MYXR1CLJTLIP4UVh_--1nKH941DmEpdYJhtBONZPvysv68fpwL-uiJOhUl4sj2Hw1UuMPhyMdGVpW2L2678P5zud5N3hlO-qAXwMUjnJzZQ6Mgn-i7-o4TDycO7u_17-aIp01d20tGatuYzR1q6-oPRLHl5yWcfcE5br8oJTLxtaeGgPzZtJs1EtfBS0g_DsQwDkUJWtAedMELPWNR7ZggvaZnUtxCFpvBrQd8na4Q6dYoOrFaTuwRwFCTchgKF91tupWxNIahpMgaUGSsJF00rAVK6mNFtKJsB9GjFtJ0-PwJfe7BwUausQyINrUKoZcMEuiqmKJ9gj4g


###
POST http://localhost:8080/api/proxy/res
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMTEiLCJleHAiOjE3MzM3Njc4NzcsImlhdCI6MTczMzczMTg3Nywic2NvcGUiOiIifQ.rt386YK-MYXR1CLJTLIP4UVh_--1nKH941DmEpdYJhtBONZPvysv68fpwL-uiJOhUl4sj2Hw1UuMPhyMdGVpW2L2678P5zud5N3hlO-qAXwMUjnJzZQ6Mgn-i7-o4TDycO7u_17-aIp01d20tGatuYzR1q6-oPRLHl5yWcfcE5br8oJTLxtaeGgPzZtJs1EtfBS0g_DsQwDkUJWtAedMELPWNR7ZggvaZnUtxCFpvBrQd8na4Q6dYoOrFaTuwRwFCTchgKF91tupWxNIahpMgaUGSsJF00rAVK6mNFtKJsB9GjFtJ0-PwJfe7BwUausQyINrUKoZcMEuiqmKJ9gj4g
Content-Type: application/json

{
  "date": "2024-12-09",
  "seat": "78873",
  "start": "now",
  "end": "1350"
}

###
GET http://localhost:8080/api/proxy/time?id=78873&date=2024-12-09
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMTEiLCJleHAiOjE3MzM3Njc4NzcsImlhdCI6MTczMzczMTg3Nywic2NvcGUiOiIifQ.rt386YK-MYXR1CLJTLIP4UVh_--1nKH941DmEpdYJhtBONZPvysv68fpwL-uiJOhUl4sj2Hw1UuMPhyMdGVpW2L2678P5zud5N3hlO-qAXwMUjnJzZQ6Mgn-i7-o4TDycO7u_17-aIp01d20tGatuYzR1q6-oPRLHl5yWcfcE5br8oJTLxtaeGgPzZtJs1EtfBS0g_DsQwDkUJWtAedMELPWNR7ZggvaZnUtxCFpvBrQd8na4Q6dYoOrFaTuwRwFCTchgKF91tupWxNIahpMgaUGSsJF00rAVK6mNFtKJsB9GjFtJ0-PwJfe7BwUausQyINrUKoZcMEuiqmKJ9gj4g

###
GET http://localhost:8080/api/proxy/seats?room=5&date=2024-12-09
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMTEiLCJleHAiOjE3MzM5NjIxOTEsImlhdCI6MTczMzkyNjE5MSwic2NvcGUiOiIifQ.fVF3Dz0IS6F42tI0v256p30PZXgIh-7eoEBomWaWZ-arm9LE2thRK2TcWfy-_-8lcFsRraEgVOZkKi0IgtFBBUax_SaICOkFAnC0Vw2v_4MX7vhUsuJZ9EkoW5dUtYID3fRWwedgJIyhglU-Om9Marv15ODnSvsRQuQU_OAk5Tsyk_8f99IhRgcQ6O3lh6teN6ilw4caUObRlcyw5HoAWS05MuUbwKmoK5lbA74R8VykI4p3DxtxDoPYXHFTdvNeExIaL_8-3t8jVlf78YwjWzrg6hsgNRBl9l_qrO1BhzkDTX7mVTl5Atczg44zTpidCysyjy7MjVicXHCJB9pgHg

###
#@roomCrawlingDto = {"building":1，"floor":"1"，"onDate":"2024-12-09"}
GET http://localhost:8080/api/proxy/rooms?building=1&floor=1&onDate=2024-12-11
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMTEiLCJleHAiOjE3MzM5MjU0MTcsImlhdCI6MTczMzg4OTQxNywic2NvcGUiOiIifQ.CbVAL3BjWBlgTXqPF_Q_dYJH2w7MswvLSWRafjNS79cvGLoC3by4rSNF3eVFQEs592SJkmvQUlTtRn-VWlLRjtWJEJUuUuPWsPnsOXPAafGFLHyp7FyrnBbLHmeUVlz_FlVnJZ8gYoyBAA32WtQHu4scog_THS9sQ2oRzy4Ms5SFxEOuXfsW5zq2E9YQPn7as9oIYZciMtZgdkfebLn7964wtje2YWbEj2PsHMwL7uBht4IuEaZfR1bMCfvRb-_kgG-o9UYPp98R7-X8nVDajzpyVNH-zMBT2KUlXHGFJ9BQkM5Iq5nN0Ci06FJkFA78DQ4QuRpXBGyzWAWQbqWSsg

###
#@roomCrawlingDto = {"building":1，"floor":"1"，"onDate":"2024-12-09"}
GET http://localhost:8080/api/proxy/reserveHistory
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMTEiLCJleHAiOjE3MzQxMzEwMjksImlhdCI6MTczNDA5NTAyOSwic2NvcGUiOiIifQ.w4Ou-foK_QrKnDTzG58AYAj6X0Y2AQq_tSayzUcZ-6lvQZlBVlr8xMv5710yQDeYUiy_Kbpxo_MFCir3bta2NOBAlJ7YdI2QvKsal1hXEs-Ml5Li08YELtzT3pP6jFSrc6UXqCkVflvPbwtrL_JT4kHN-nTOmmhJhiT5fVGVoO7S1OnOLVTSz177MWL_e-XQ4kU91Cy5tbaGpVD08KX00vJHZ-TQvfLrgxhKZmvqfA5V2sz-xIfEHX13ix56l5NT-zmZJ7pvSWv6MEKUlY9y96aXzVEWo0VBT6ZulEuOLsOg4j7TZtQAAo4EdSUZYVyK_uXukTXbNRLXUAYKkrwGKQ